### ISSUE TITLE
Use Random to get Colors

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/VividHues#1]
#### Use random to:
- [x] Choose a random color
- [x] Print a string in many random colors
#### Another feature to add:
- [x] Iterate over characters for rainbow effect
#### Additionally:
- [x] Add relevant info & code to the ```README.md``` documentation

**Comment by esouidi** [comment]
Hi, I want to work on this, can you assign me ?

**Comment by KennyOliver** [comment]
Awesome! Glad to have you on board! :smile:
You can do all of those 4 tasks if you'd like. I've reordered them in terms of least to most difficult.

#### Tips/More Info
You just need to modify ```__init__.py```:
- Add these 3 new functions as methods of the ```Clr``` class:
    - Give the methods appropriate names (i.e., ```Clr.random()```, ```Clr.jazzy(string)```, ```Clr.rainbow(string)```)

Don't forget to update the ```README.md``` documentation too, please

**Comment by esouidi** [comment]
All right, I've already started to work on it.
However, I don't really get the difference between the instruction 2 and 3. When you say rainbow effect, do you mean colors have to change on the system output ?
For the moment this is what I have : ![image](https://user-images.githubusercontent.com/75025946/144762398-3f422a51-b474-4643-9ba2-9f74848b738a.png)

**Comment by KennyOliver** [comment]
Looks cool so far but please make the functions have more succinct names for ease of use.

For rainbow:
Each character has to change in color, e.g. "hello world" would be colored red, orange, yellow, green, etc. for each character
My bad... rainbow isn't random, but my issue made it seem like it was.

Like below:
![images](https://user-images.githubusercontent.com/70860732/144762465-1195fd13-82b9-4af3-91bc-d5518fdc5e1b.jpg)
(couldn't find a good pic)

For random colors:
Each character is assigned a random color - even if two adjacent characters are given the same color code.

**Comment by KennyOliver** [comment]
Closed with #3 thanks for contributing

**Comment by KennyOliver** [comment]
@esouidi your code is now on [Test PyPi](https://test.pypi.org/project/VividHues) as part of the package :+1:
Hopefully it'll eventually be updated officially to [PyPi](https://pypi.org/project/VividHues/)
